name: AUTO docs deploy to netlify
on: [pull_request, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy docs to Netlify.
    steps:
      - uses: actions/checkout@v2
      - name: Install packages.
        run: yarn install 
      - name: Deploy built docs-app to Netlify.
        id: deploy_to_netlify
        continue-on-error: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN__PR_PREVIEW_REPO }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        # run: echo "::set-output name=url::$(npx netlify deploy --dir ./page | grep "Website Draft URL" | awk '{print $4}')"
        run: exit 1
      - name: Test previous step output.
#         if: ${{ steps.deploy_to_netlify.outcome == success }}
        run: echo ${{ steps.deploy_to_netlify.outcome }}
      # - name: Add Comment to PR with the preview URL.
      #   uses: actions-cool/maintain-one-comment@v2.0.0
      #   with: 
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     body: |
      #       Preview URL: ${{ steps.deploy_to_netlify.outputs.url }}

